# Generated by Django 4.0.4 on 2022-05-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_surname', models.CharField(max_length=50)),
                ('animal_type', models.CharField(max_length=50)),
                ('phone', models.IntegerField(blank=True)),
                ('reservation_date', models.DateTimeField()),
            ],
        ),
    ]
