# Generated by Django 4.0.4 on 2022-05-20 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_vet_reservation_vet_name_alter_reservation_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data opublikowania'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Treść posta'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł posta'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='animal_name',
            field=models.CharField(max_length=50, verbose_name='Imię zwierzęcia'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='animal_type',
            field=models.CharField(max_length=50, verbose_name='Typ zwierzęcia'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='owner_name',
            field=models.CharField(max_length=50, verbose_name='Imię właściciela'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='owner_surname',
            field=models.CharField(max_length=50, verbose_name='Nazwisko właściciela'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=9, verbose_name='Numer komórkowy'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data rezerwacji'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='vet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Weterynarz'),
        ),
    ]
