# Generated by Django 4.0.4 on 2022-05-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_post_author_alter_post_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię zwierzęcia')),
                ('sex', models.BooleanField(verbose_name='Płeć zwierzęcia')),
                ('type', models.CharField(max_length=50, verbose_name='Typ zwierzęcia')),
                ('breed', models.CharField(max_length=200, verbose_name='Rasa zwierzęcia')),
                ('neutered', models.BooleanField(verbose_name='Czy wykastrowany/sterylizowany?')),
                ('chip', models.BooleanField(verbose_name='Czy posiada czip?')),
                ('additional_info', models.CharField(max_length=500, verbose_name='Dodatkowe informacje')),
                ('owner', models.CharField(max_length=100, verbose_name='Właściciel')),
                ('contact', models.CharField(max_length=50, verbose_name='Kontakt')),
                ('mail', models.CharField(max_length=50, verbose_name='Adres mailowy')),
                ('address', models.CharField(max_length=50, verbose_name='Adres zamieszkania')),
            ],
        ),
    ]
