# Generated by Django 4.0.4 on 2022-05-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_animalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię zwierzęcia')),
                ('sex', models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], max_length=6, verbose_name='Płeć zwierzęcia')),
                ('type', models.CharField(max_length=50, verbose_name='Typ zwierzęcia')),
                ('breed', models.CharField(max_length=200, verbose_name='Rasa zwierzęcia')),
                ('neutered', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=6, verbose_name='Czy kastrowany/sterylizowany?')),
                ('chip', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=6, verbose_name='Czy posiada chip?')),
                ('additional_info', models.CharField(max_length=500, verbose_name='Dodatkowe informacje')),
                ('owner', models.CharField(max_length=100, verbose_name='Właściciel')),
                ('contact', models.CharField(max_length=9, verbose_name='Kontakt')),
                ('mail', models.CharField(max_length=50, verbose_name='Adres mailowy')),
                ('address', models.CharField(max_length=50, verbose_name='Adres zamieszkania')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Imię właściciela')),
                ('owner_surname', models.CharField(max_length=50, verbose_name='Nazwisko właściciela')),
                ('phone', models.CharField(blank=True, max_length=9, verbose_name='Numer komórkowy')),
                ('mail', models.CharField(max_length=50, verbose_name='Adres mailowy')),
                ('address', models.CharField(max_length=50, verbose_name='Adres zamieszkania')),
                ('RODO', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=6, verbose_name='Zgoda RODO?')),
            ],
        ),
        migrations.DeleteModel(
            name='AnimalInfo',
        ),
    ]
