# Generated by Django 4.0.4 on 2022-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_animal_owner_delete_animalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='owner',
        ),
        migrations.AddField(
            model_name='animal',
            name='owner_name',
            field=models.CharField(default='wpisz imie wlasciciela', max_length=50, verbose_name='Imię właściciela'),
        ),
        migrations.AddField(
            model_name='animal',
            name='owner_surname',
            field=models.CharField(default='wpisz nazwisko wlasciciela', max_length=50, verbose_name='Nazwisko właściciela'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='chip',
            field=models.CharField(choices=[('nie', 'TAK'), ('nie', 'NIE')], max_length=6, verbose_name='Czy posiada chip?'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='neutered',
            field=models.CharField(choices=[('nie', 'TAK'), ('nie', 'NIE')], max_length=6, verbose_name='Czy kastrowany/sterylizowany?'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('żeńska', 'ŻEŃSKA'), ('męska', 'MĘSKA')], max_length=6, verbose_name='Płeć zwierzęcia'),
        ),
    ]
