# Generated by Django 4.0.4 on 2022-05-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_owner_remove_animal_owner_animal_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='RODO',
            field=models.CharField(choices=[('nie', 'TAK'), ('nie', 'NIE')], default=1, max_length=6, verbose_name='Zgoda na przetwarzanie danych?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner_name',
            field=models.CharField(default='Wpisz imię właściciela', max_length=50, verbose_name='Imię właściciela'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner_surname',
            field=models.CharField(default='Wpisz nazwisko właściciela', max_length=50, verbose_name='Nazwisko właściciela'),
        ),
    ]
