# Generated by Django 4.0.4 on 2022-05-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_animal_rodo_alter_animal_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='nr_chip',
            field=models.CharField(default=1, max_length=20, verbose_name='Numer chip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner_name',
            field=models.CharField(max_length=50, verbose_name='Imię właściciela'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner_surname',
            field=models.CharField(max_length=50, verbose_name='Nazwisko właściciela'),
        ),
    ]
