# Generated by Django 4.0.4 on 2022-05-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_animal_nr_chip_alter_animal_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nr_chip',
            field=models.CharField(max_length=15, verbose_name='Numer chip'),
        ),
    ]
