# Generated by Django 4.0.4 on 2022-05-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_animal_nr_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('pies', 'PIES'), ('kot', 'KOT'), ('gryzoń', 'GRYZOŃ'), ('królik', 'KRÓLIK'), ('gad', 'GAD'), ('fretka', 'FRETKA'), ('ptak', 'PTAK'), ('inne', 'INNE')], max_length=6, verbose_name='Typ zwierzęcia'),
        ),
    ]
