# Generated by Django 4.0.4 on 2022-05-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_reservation_animals_delete_visitshistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='animals',
            new_name='animal',
        ),
        migrations.AddField(
            model_name='reservation',
            name='owner',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='app.animal'),
        ),
    ]
