# Generated by Django 4.0.4 on 2022-05-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_animals_reservation_animal_reservation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='owner',
        ),
    ]
