# Generated by Django 4.0.4 on 2022-05-26 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_animal_rodo_alter_animal_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='visit_type',
            field=models.CharField(choices=[('Wizyta kontrolna', 'WIZYTA KONTROLNA'), ('Konsultacja chirurgiczna', 'KONSULTACJA CHIRURGICZNA')], default='Typ wizyty...', max_length=50, verbose_name='Typ wizyty'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='animal',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.animal', verbose_name='Wybierz z bazy'),
        ),
    ]
