# Generated by Django 4.0.4 on 2022-05-27 14:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_reservation_visit_type_alter_reservation_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=9, verbose_name='Numer komórkowy'),
        ),
    ]
