# Generated by Django 4.0.4 on 2022-05-30 12:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_post_text_alter_reservation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='visit_info',
            field=models.CharField(default='Brak informacji na temat tej wizyty', max_length=3000, verbose_name='Dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tekst'),
        ),
    ]
