# Generated by Django 4.0.4 on 2022-05-30 13:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_reservation_visit_info_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='visit_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tekst'),
        ),
    ]
