# Generated by Django 4.0.4 on 2022-05-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_reservation_visit_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='vet_name',
        ),
        migrations.AddField(
            model_name='vet',
            name='description',
            field=models.CharField(default='Opis..', max_length=200),
        ),
        migrations.AddField(
            model_name='vet',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vet',
            name='photo',
            field=models.ImageField(default=1, upload_to='vet-photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vet',
            name='specialization',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vet')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='working_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.workingtime', verbose_name='Data rezerwacji'),
        ),
    ]
