# Generated by Django 4.0.4 on 2022-06-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_reservation_animal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='visit_type',
            field=models.CharField(choices=[('Wizyta kontrolna', 'WIZYTA KONTROLNA'), ('Konsultacja chirurgiczna', 'KONSULTACJA CHIRURGICZNA'), ('Zabieg', 'ZABIEG')], default='Typ wizyty...', max_length=50, verbose_name='Typ wizyty'),
        ),
    ]
