# Generated by Django 4.0.4 on 2022-06-09 17:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_agenda_alter_reservation_visit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='visit_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cel wizyty/Dodatkowe informacje'),
        ),
    ]
