# Generated by Django 4.0.4 on 2022-06-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_reservation_visit_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'grafik', 'verbose_name_plural': 'grafiki'},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'zwierzę', 'verbose_name_plural': 'zwierzęta'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posty'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'rezerwacja', 'verbose_name_plural': 'rezerwacje'},
        ),
        migrations.AlterModelOptions(
            name='vet',
            options={'verbose_name': 'weterynarz', 'verbose_name_plural': 'weterynarze'},
        ),
        migrations.AlterModelOptions(
            name='workingtime',
            options={'verbose_name': 'czas pracy', 'verbose_name_plural': 'Czas pracy weterynarzy'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='animal',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='contact',
            field=models.CharField(max_length=9, verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='visit_type',
            field=models.CharField(choices=[('Wizyta kontrolna', 'WIZYTA KONTROLNA'), ('Konsultacja chirurgiczna', 'KONSULTACJA CHIRURGICZNA')], default='Typ wizyty...', max_length=50, verbose_name='Typ wizyty'),
        ),
    ]
