# Generated by Django 4.0.4 on 2022-06-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_agenda_options_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.animal'),
        ),
    ]
